title: Lhaverse
description: A universe of sacred mountains.
url: "https://lhaverse.cn"
baseurl: ""
lang: en
timezone: Asia/Shanghai

markdown: kramdown
permalink: pretty

exclude:
  - design
  - Gemfile
  - Gemfile.lock
  - task_plan.md
  - findings.md
  - progress.md
